"use client";

import { useEffect, useRef, useState } from "react";
import QrScanner from "qr-scanner";

interface AttendeeQrScannerProps {
  onEventId: (eventId: string) => void;
  onCancel: () => void;
}

/**
 * Extract an eventId from a scanned QR payload. The QR codes generated by the
 * backend encode a registration URL like:
 *   {FRONTEND_URL}/auth/attendee/register?eventId=cuidxxx&eventName=...
 * We accept either a full URL containing `eventId=...` or a bare event id.
 */
function extractEventId(raw: string): string | null {
  const trimmed = raw.trim();
  if (!trimmed) return null;
  try {
    const url = new URL(trimmed);
    const fromQuery = url.searchParams.get("eventId");
    if (fromQuery) return fromQuery;
  } catch {
    // not a URL — fall through and treat as a raw id
  }
  // Heuristic: cuid/cuid2 ids are alphanumeric, 20-30 chars, no spaces.
  if (/^[a-z0-9]{16,40}$/i.test(trimmed)) return trimmed;
  return null;
}

export function AttendeeQrScanner({ onEventId, onCancel }: AttendeeQrScannerProps) {
  const videoRef = useRef<HTMLVideoElement | null>(null);
  const scannerRef = useRef<QrScanner | null>(null);
  const [status, setStatus] = useState<"idle" | "starting" | "scanning" | "error">("idle");
  const [errorMsg, setErrorMsg] = useState<string>("");
  const handledRef = useRef(false);

  useEffect(() => {
    let cancelled = false;
    const video = videoRef.current;
    if (!video) return;

    setStatus("starting");
    setErrorMsg("");

    QrScanner.hasCamera()
      .then(async (hasCamera) => {
        if (cancelled) return;
        if (!hasCamera) {
          setStatus("error");
          setErrorMsg("No camera was detected on this device.");
          return;
        }
        const scanner = new QrScanner(
          video,
          (result) => {
            if (handledRef.current) return;
            const eventId = extractEventId(result.data);
            if (!eventId) {
              setErrorMsg("That QR code didn't contain a valid event link. Try another code or use Event ID.");
              return;
            }
            handledRef.current = true;
            scanner.stop();
            onEventId(eventId);
          },
          {
            highlightScanRegion: true,
            highlightCodeOutline: true,
            preferredCamera: "environment",
            maxScansPerSecond: 5,
          },
        );
        scannerRef.current = scanner;
        try {
          await scanner.start();
          if (cancelled) {
            scanner.stop();
            return;
          }
          setStatus("scanning");
        } catch (err) {
          const message =
            err instanceof Error && /denied|permission/i.test(err.message)
              ? "Camera permission was denied. Allow camera access in your browser and try again."
              : "Could not start the camera. Make sure no other app is using it and try again.";
          setStatus("error");
          setErrorMsg(message);
        }
      })
      .catch(() => {
        if (cancelled) return;
        setStatus("error");
        setErrorMsg("Could not check for a camera on this device.");
      });

    return () => {
      cancelled = true;
      const s = scannerRef.current;
      if (s) {
        s.stop();
        s.destroy();
        scannerRef.current = null;
      }
    };
  }, [onEventId]);

  return (
    <div className="rounded-2xl border border-emerald-200 bg-emerald-50/40 p-4">
      <div className="relative overflow-hidden rounded-xl bg-black aspect-square">
        <video
          ref={videoRef}
          className="h-full w-full object-cover"
          playsInline
          muted
        />
        {status === "starting" && (
          <div className="absolute inset-0 flex items-center justify-center bg-black/60 text-white text-sm">
            Starting camera…
          </div>
        )}
      </div>

      {status === "scanning" && (
        <p className="mt-3 text-center text-xs font-medium text-emerald-800">
          Point your camera at the event QR code.
        </p>
      )}

      {status === "error" && errorMsg && (
        <p className="mt-3 rounded-xl bg-red-50 border border-red-200 px-3 py-2 text-xs text-red-700">
          {errorMsg}
        </p>
      )}

      {status === "scanning" && errorMsg && (
        <p className="mt-2 rounded-xl bg-amber-50 border border-amber-200 px-3 py-2 text-xs text-amber-800">
          {errorMsg}
        </p>
      )}

      <div className="mt-3 flex items-center justify-between gap-2">
        <button
          type="button"
          onClick={onCancel}
          className="rounded-xl px-3 py-2 text-xs font-semibold text-emerald-800 hover:bg-emerald-100 transition-colors"
        >
          ← Back
        </button>
        <p className="text-[10px] text-emerald-700/70">
          Tip: hold the code about 15 cm from the camera.
        </p>
      </div>
    </div>
  );
}
